services:
  node-ts-basics.local:
    image: queirozjamessom/node-ts-basics.local
    container_name: node-ts-basics.local
    build: .
    ports: ["3435:3435"]
    command: npm run dev
    volumes: ["./node_modules:/home/app/node_modules"]